### ISSUE TITLE
Support for characters such as 'Ä' in room names

### ISSUE THREAD

**Issue by henrikland** [storypalette/storypalette-performer-touch#11]

**Comment by henrikland** [comment]
Room names somehow get messed up when fetched from db.

room: {
  name: "åäöüçÅÄÖÜÇ",
  ...
}

console.log(room.name); //Ã¥Ã¤Ã¶Ã¼Ã§ÃÃÃÃÃ

**Comment by snawbel** [comment]
This also affects the editor and makes Lindängen looks ugly. @ravachol Perhaps you could have a look at this next week?

![image](https://cloud.githubusercontent.com/assets/554578/13874135/22b92480-ecf6-11e5-9039-831c2571a2d0.png)

**Comment by snawbel** [comment]
Looks ok here: http://api.storypalette.net/v1/organisations. HTML character encoding? Hmm...

**Comment by ravachol** [comment]
I'll look into it.

**Comment by ravachol** [comment]
Fixed this it was due to decoding of the jsonwebtoken (which is how we get user info) being done without utf-8 support. The fix is in storypalette-editor repo
