### ISSUE TITLE
Label styling problem?

### ISSUE THREAD

**Issue by snawbel** [storypalette/storypalette-performer-touch#7]
Oxie says: "sedan paletten uppdaterades är ljudens och 
ljusets namn inte helt synliga i appen när vi skall spela upp dem. Vi 
ser bara den första bokstaven på ljuden"

**Comment by snawbel** [comment]
@ravachol Kan du kolla om det här stämmer? Om du inte har en iPad kan du kan installera senaste versionen av XCode och köra iOS simulator där för att testa.

**Comment by ravachol** [comment]
testat i XCode IOS Simulator och namnen var fullt synliga.

**Comment by ravachol** [comment]
kan det vara en specifik palett som visas fel?
